### ISSUE TITLE
Compile Error in Ubuntu Bionic 18.04

### ISSUE THREAD

**Issue by pmo-19** [strukturag/vlc-libde265#10]
Building the package `vlc-plugin-libde265` does not work in Ubuntu Bionic 18.04 and Cosmic 18.10.
It works on all previous Ubuntu releases.

```
make[3]: Entering directory '/<<PKGBUILDDIR>>'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -Wdate-time -D_FORTIFY_SOURCE=2 -DMODULE_STRING=\"de265\"  -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -Wdate-time -D_FORTIFY_SOURCE=2 -DMODULE_STRING=\"de265\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
src/codec/libde265dec.c: In function ‘Decode’:
src/codec/libde265dec.c:384:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control && (sys->late_frames > 0) &&
             ^~
src/codec/libde265dec.c:392:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control &&
             ^~
src/codec/libde265dec.c: In function ‘Open’:
src/codec/libde265dec.c:879:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘pf_decode_video’; did you mean ‘pf_queue_video’?
     dec->pf_decode_video = Decode;
          ^~~~~~~~~~~~~~~
          pf_queue_video
src/codec/libde265dec.c:886:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_need_packetized’; did you mean ‘pf_packetize’?
     dec->b_need_packetized = true;
          ^~~~~~~~~~~~~~~~~
          pf_packetize
Makefile:832: recipe for target 'src/codec/libde265_plugin_la-libde265dec.lo' failed
make[3]: *** [src/codec/libde265_plugin_la-libde265dec.lo] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>'
make[3]: *** Waiting for unfinished jobs....
make[3]: Entering directory '/<<PKGBUILDDIR>>'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265demux\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -Wdate-time -D_FORTIFY_SOURCE=2 -DMODULE_STRING=\"de265demux\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -c -o src/demux/libde265demux_plugin_la-libde265demux.lo `test -f 'src/demux/libde265demux.c' || echo './'`src/demux/libde265demux.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265demux\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -Wdate-time -D_FORTIFY_SOURCE=2 -DMODULE_STRING=\"de265demux\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -c src/demux/libde265demux.c  -fPIC -DPIC -o src/demux/.libs/libde265demux_plugin_la-libde265demux.o
src/demux/libde265demux.c: In function ‘Open’:
src/demux/libde265demux.c:118:15: error: ‘demux_t {aka struct demux_t}’ has no member named ‘b_force’
     if (!demux->b_force) {
               ^~
src/demux/libde265demux.c:139:19: warning: implicit declaration of function ‘stream_Peek’; did you mean ‘stream_Size’? [-Wimplicit-function-declaration]
     buffer_size = stream_Peek(demux->s, &buffer, DETECT_BUFFER_SIZE);
                   ^~~~~~~~~~~
                   stream_Size
src/demux/libde265demux.c: In function ‘Demux’:
src/demux/libde265demux.c:362:20: warning: implicit declaration of function ‘stream_Block’; did you mean ‘vlc_stream_Block’? [-Wimplicit-function-declaration]
     if ((p_block = stream_Block(p_demux->s, end - start)) == NULL) {
                    ^~~~~~~~~~~~
                    vlc_stream_Block
src/demux/libde265demux.c:362:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     if ((p_block = stream_Block(p_demux->s, end - start)) == NULL) {
                  ^
Makefile:853: recipe for target 'src/demux/libde265demux_plugin_la-libde265demux.lo' failed
make[3]: *** [src/demux/libde265demux_plugin_la-libde265demux.lo] Error 1
make[3]: Leaving directory '/<<PKGBUILDDIR>>'
Makefile:567: recipe for target 'all' failed
make[2]: *** [all] Error 2
dh_auto_build: make -j4 -O -j4 returned exit code 2
debian/rules:42: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 25
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:39: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
```
It looks like a structure definition problem in C and mismatch of function name ?

**Comment by undeadindustries** [comment]
Same thing happening for me in 18.04.1

**Comment by bazingarj** [comment]
make  all-am
make[1]: Entering directory '/opt/softwares/vlc-addons/vlc-libde265'
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins  -DMODULE_STRING=\"de265\"  -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins -DMODULE_STRING=\"de265\" -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -I/usr/include/vlc/plugins "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
src/codec/libde265dec.c: In function ‘Decode’:
src/codec/libde265dec.c:369:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control && (sys->late_frames > 0) &&
             ^~
src/codec/libde265dec.c:377:13: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_pace_control’
     if (!dec->b_pace_control &&
             ^~
src/codec/libde265dec.c: In function ‘Open’:
src/codec/libde265dec.c:864:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘pf_decode_video’; did you mean ‘pf_queue_video’?
     dec->pf_decode_video = Decode;
          ^~~~~~~~~~~~~~~
          pf_queue_video
src/codec/libde265dec.c:871:10: error: ‘decoder_t {aka struct decoder_t}’ has no member named ‘b_need_packetized’; did you mean ‘pf_packetize’?
     dec->b_need_packetized = true;
          ^~~~~~~~~~~~~~~~~
          pf_packetize
Makefile:828: recipe for target 'src/codec/libde265_plugin_la-libde265dec.lo' failed
make[1]: *** [src/codec/libde265_plugin_la-libde265dec.lo] Error 1
make[1]: Leaving directory '/opt/softwares/vlc-addons/vlc-libde265'
Makefile:567: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mietzen** [comment]
Not Just Ubuntu Fedora 29 is broken too:

```
make  all-am
make[1]: Entering directory '/home/nils/Downloads/vlc-libde265-0.1.7'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE   -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE  -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
src/codec/libde265dec.c: In function 'Decode':
src/codec/libde265dec.c:384:13: error: 'decoder_t' {aka 'struct decoder_t'} has no member named 'b_pace_control'
     if (!dec->b_pace_control && (sys->late_frames > 0) &&
             ^~
src/codec/libde265dec.c:392:13: error: 'decoder_t' {aka 'struct decoder_t'} has no member named 'b_pace_control'
     if (!dec->b_pace_control &&
             ^~
src/codec/libde265dec.c: In function 'Open':
src/codec/libde265dec.c:879:10: error: 'decoder_t' {aka 'struct decoder_t'} has no member named 'pf_decode_video'; did you mean 'pf_queue_video'?
     dec->pf_decode_video = Decode;
          ^~~~~~~~~~~~~~~
          pf_queue_video
src/codec/libde265dec.c:886:10: error: 'decoder_t' {aka 'struct decoder_t'} has no member named 'b_need_packetized'; did you mean 'pf_packetize'?
     dec->b_need_packetized = true;
          ^~~~~~~~~~~~~~~~~
          pf_packetize
make[1]: *** [Makefile:724: src/codec/libde265_plugin_la-libde265dec.lo] Error 1
make[1]: Leaving directory '/home/nils/Downloads/vlc-libde265-0.1.7'
make: *** [Makefile:447: all] Error 2

```

**Comment by damian101** [comment]
Looks like I get the same error as @mietzen on Reborn OS (Arch based):
```make  all-am
make[1]: Entering directory '/home/damian101/Downloads/vlc-libde265-master'
/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE   -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE  -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
src/codec/libde265dec.c: In function ‘Decode’:
src/codec/libde265dec.c:369:13: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_pace_control’
     if (!dec->b_pace_control && (sys->late_frames > 0) &&
             ^~
src/codec/libde265dec.c:377:13: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_pace_control’
     if (!dec->b_pace_control &&
             ^~
src/codec/libde265dec.c: In function ‘Open’:
src/codec/libde265dec.c:864:10: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘pf_decode_video’; did you mean ‘pf_queue_video’?
     dec->pf_decode_video = Decode;
          ^~~~~~~~~~~~~~~
          pf_queue_video
src/codec/libde265dec.c:871:10: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_need_packetized’; did you mean ‘pf_packetize’?
     dec->b_need_packetized = true;
          ^~~~~~~~~~~~~~~~~
          pf_packetize
make[1]: *** [Makefile:851: src/codec/libde265_plugin_la-libde265dec.lo] Error 1
make[1]: Leaving directory '/home/damian101/Downloads/vlc-libde265-master'
make: *** [Makefile:584: all] Error 2
```

**Comment by annahri** [comment]
Same problem on Solus 4.1 Fortitude

**Comment by jellium** [comment]
> Looks like I get the same error as @mietzen on Reborn OS (Arch based):
> 
> ```makefile
> make[1]: Entering directory '/home/damian101/Downloads/vlc-libde265-master'
> /bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.  -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE   -DMODULE_STRING=\"de265\"  -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE  -DVLC_MODULE_COPYRIGHT="\"Copyright \(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c -o src/codec/libde265_plugin_la-libde265dec.lo `test -f 'src/codec/libde265dec.c' || echo './'`src/codec/libde265dec.c
> libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE -DMODULE_STRING=\"de265\" -I/usr/include/vlc/plugins -D__PLUGIN__ -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_THREAD_SAFE "-DVLC_MODULE_COPYRIGHT=\"Copyright \\(c) struktur AG\"" -DVLC_MODULE_LICENSE=\"LGPL\" -MT src/codec/libde265_plugin_la-libde265dec.lo -MD -MP -MF src/codec/.deps/libde265_plugin_la-libde265dec.Tpo -c src/codec/libde265dec.c  -fPIC -DPIC -o src/codec/.libs/libde265_plugin_la-libde265dec.o
> src/codec/libde265dec.c: In function ‘Decode’:
> src/codec/libde265dec.c:369:13: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_pace_control’
>      if (!dec->b_pace_control && (sys->late_frames > 0) &&
>              ^~
> src/codec/libde265dec.c:377:13: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_pace_control’
>      if (!dec->b_pace_control &&
>              ^~
> src/codec/libde265dec.c: In function ‘Open’:
> src/codec/libde265dec.c:864:10: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘pf_decode_video’; did you mean ‘pf_queue_video’?
>      dec->pf_decode_video = Decode;
>           ^~~~~~~~~~~~~~~
>           pf_queue_video
> src/codec/libde265dec.c:871:10: error: ‘decoder_t’ {aka ‘struct decoder_t’} has no member named ‘b_need_packetized’; did you mean ‘pf_packetize’?
>      dec->b_need_packetized = true;
>           ^~~~~~~~~~~~~~~~~
>           pf_packetize
> make[1]: *** [Makefile:851: src/codec/libde265_plugin_la-libde265dec.lo] Error 1
> make[1]: Leaving directory '/home/damian101/Downloads/vlc-libde265-master'
> make: *** [Makefile:584: all] Error 2
> ```

Same problem on Debian Buster despite successful compilation of (your) libde265 package. Any hint?

**Comment by folkien** [comment]
Is this really supported in 18.04? Last commit from master is from 2015.
